export const planets = [
  {
    id: "mercury",
    name: "Mercury",
    description: "The smallest and fastest planet, zipping around the Sun in only 88 Earth days.",
    distance: "57.9M km",
    gravity: "3.7 m/s²",
    temp: "-180°C to 430°C",
    moons: 0,
    facts: ["Has wrinkles called lobate scarps.", "No atmosphere to retain heat."],
    color: "#a8a8a8",
    size: 0.38,
    orbitRadius: 100,
    orbitSpeed: 8.8,
  },
  {
    id: "venus",
    name: "Venus",
    description: "Earth's toxic twin, with a thick atmosphere that traps heat in a runaway greenhouse effect.",
    distance: "108.2M km",
    gravity: "8.87 m/s²",
    temp: "465°C avg",
    moons: 0,
    facts: ["Spins backwards compared to most planets.", "Hottest planet in the solar system."],
    color: "#e3bb76",
    size: 0.95,
    orbitRadius: 140,
    orbitSpeed: 22.5,
  },
  {
    id: "earth",
    name: "Earth",
    description: "Our home planet, the only place we know of so far that's inhabited by living things.",
    distance: "149.6M km",
    gravity: "9.81 m/s²",
    temp: "-88°C to 58°C",
    moons: 1,
    facts: ["Only planet with liquid water on the surface.", "Name does not come from Greek/Roman mythology."],
    color: "#4b9be3",
    size: 1,
    orbitRadius: 180,
    orbitSpeed: 36.5,
  },
  {
    id: "mars",
    name: "Mars",
    description: "A dusty, cold, desert world with a very thin atmosphere.",
    distance: "227.9M km",
    gravity: "3.71 m/s²",
    temp: "-125°C to 20°C",
    moons: 2,
    facts: ["Home to the largest volcano in the solar system.", "Sunsets on Mars appear blue."],
    color: "#c1440e",
    size: 0.53,
    orbitRadius: 220,
    orbitSpeed: 68.7,
  },
  {
    id: "jupiter",
    name: "Jupiter",
    description: "More than twice as massive as all the other planets combined.",
    distance: "778.5M km",
    gravity: "24.79 m/s²",
    temp: "-108°C",
    moons: 95,
    facts: ["Has a storm that has raged for over 300 years.", "Fastest spinning planet in the solar system."],
    color: "#d39c7e",
    size: 2.2,
    orbitRadius: 300,
    orbitSpeed: 433.2,
  },
  {
    id: "saturn",
    name: "Saturn",
    description: "Adorned with a dazzling, complex system of icy rings.",
    distance: "1.4B km",
    gravity: "10.44 m/s²",
    temp: "-178°C avg",
    moons: 146,
    facts: ["Could float in water because it is mostly gas.", "Winds in the upper atmosphere reach 500 m/s."],
    color: "#ead6b8",
    size: 1.8,
    orbitRadius: 380,
    orbitSpeed: 1075.9,
    hasRings: true,
  },
  {
    id: "uranus",
    name: "Uranus",
    description: "An ice giant that rotates on its side.",
    distance: "2.9B km",
    gravity: "8.69 m/s²",
    temp: "-216°C avg",
    moons: 27,
    facts: ["Rotates at a nearly 90-degree angle from the plane of its orbit.", "First planet discovered with a telescope."],
    color: "#4b70dd",
    size: 1.2,
    orbitRadius: 440,
    orbitSpeed: 3068.7,
  },
  {
    id: "neptune",
    name: "Neptune",
    description: "Dark, cold, and whipped by supersonic winds.",
    distance: "4.5B km",
    gravity: "11.15 m/s²",
    temp: "-214°C avg",
    moons: 16,
    facts: ["Only planet found by mathematical prediction rather than empirical observation.", "Has supersonic winds."],
    color: "#274687",
    size: 1.15,
    orbitRadius: 500,
    orbitSpeed: 6019.0,
  }
];

export const facts = [
  "The Sun accounts for 99.86% of the solar system's total mass.",
  "One million Earths could fit inside the Sun.",
  "A day on Venus is longer than a year on Venus.",
  "Neutron stars can spin 600 times per second.",
  "The largest known star, UY Scuti, is 1,700 times larger than the Sun.",
  "There is a giant cloud of alcohol in space (Sagittarius B2).",
  "Sound cannot travel in space.",
  "The Milky Way galaxy is 100,000 light-years wide.",
  "There are more stars in the universe than grains of sand on Earth.",
  "Saturn's rings are made of ice and rock, and are only about 30 feet thick.",
  "Jupiter's Great Red Spot is a storm that has raged for at least 350 years.",
  "The footprints left on the Moon will last for millions of years.",
  "A full NASA space suit costs $12 million.",
  "The Sun is so large that about 1.3 million Earths could fit inside it.",
  "Light from the Sun takes 8 minutes and 20 seconds to reach Earth.",
  "The Andromeda Galaxy is on a collision course with the Milky Way.",
  "Black holes don't actually suck — they just have immense gravity.",
  "The International Space Station travels at 28,000 km/h.",
  "You could fit all the planets in the solar system between Earth and the Moon.",
  "Space is completely silent.",
  "The universe is approximately 13.8 billion years old.",
  "Olympus Mons on Mars is the tallest volcano in the solar system.",
  "Europa (Jupiter's moon) likely has a subsurface ocean with more water than Earth.",
  "A teaspoon of neutron star material would weigh 10 billion tons.",
  "The Voyager 1 spacecraft is the most distant man-made object from Earth.",
  "There are 8 planets, 5 dwarf planets, and millions of small objects in our solar system.",
  "Mercury has no atmosphere, which is why it has such extreme temperature swings.",
  "The Hubble Space Telescope can see galaxies 13.4 billion light-years away.",
  "Dark matter makes up about 27% of the universe, yet we cannot directly observe it.",
  "If the Sun were the size of a white blood cell, the Milky Way would be the size of the continental US."
];

export const quizQuestions = [
  { q: "What is the largest planet in the solar system?", a: ["Jupiter", "Saturn", "Neptune", "Earth"], correct: 0 },
  { q: "How many moons does Mars have?", a: ["0", "1", "2", "3"], correct: 2 },
  { q: "What is the closest star to Earth?", a: ["Sirius", "Proxima Centauri", "Alpha Centauri A", "The Sun"], correct: 3 },
  { q: "Which planet is known as the Red Planet?", a: ["Venus", "Jupiter", "Mars", "Saturn"], correct: 2 },
  { q: "What is the name of our galaxy?", a: ["Andromeda", "Triangulum", "Milky Way", "Whirlpool"], correct: 2 },
  { q: "How long does light from the Sun take to reach Earth?", a: ["8 seconds", "8 minutes", "8 hours", "8 days"], correct: 1 },
  { q: "Which planet has the most moons?", a: ["Jupiter", "Saturn", "Uranus", "Neptune"], correct: 1 },
  { q: "What is the Great Red Spot?", a: ["A volcano on Mars", "A storm on Jupiter", "A crater on Venus", "A moon of Saturn"], correct: 1 },
  { q: "Which is the smallest planet?", a: ["Mars", "Venus", "Pluto", "Mercury"], correct: 3 },
  { q: "What planet has the largest volcano in the solar system?", a: ["Earth", "Mars", "Venus", "Jupiter"], correct: 1 },
  { q: "What is a light-year?", a: ["Time it takes for light to reach Earth", "Distance light travels in one year", "Speed of light", "A year with more sunlight"], correct: 1 },
  { q: "Which planet spins on its side?", a: ["Venus", "Uranus", "Neptune", "Saturn"], correct: 1 },
  { q: "How old is the universe approximately?", a: ["4.6 billion years", "13.8 billion years", "100 billion years", "1 trillion years"], correct: 1 },
  { q: "What makes up Saturn's rings?", a: ["Gas and dust", "Ice and rock", "Pure diamonds", "Magnetic fields"], correct: 1 },
  { q: "Which moon has the best conditions for life?", a: ["Titan", "Europa", "Io", "Ganymede"], correct: 1 },
  { q: "What was the first country to send a human to space?", a: ["USA", "China", "USSR/Russia", "UK"], correct: 2 },
  { q: "What is the name of the first human on the Moon?", a: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"], correct: 3 },
  { q: "What is the event horizon of a black hole?", a: ["The center", "The point of no return", "The accretion disk", "The jet stream"], correct: 1 },
  { q: "What percentage of the solar system's mass does the Sun hold?", a: ["50%", "75%", "90%", "99.86%"], correct: 3 },
  { q: "What shape is the Milky Way galaxy?", a: ["Elliptical", "Spiral", "Irregular", "Lenticular"], correct: 1 }
];
